//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBookingDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatu
    {
        public int BookingId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string ManagerStatus { get; set; }
        public string CostInvolved { get; set; }
        public string TravelAgentStatus { get; set; }
    
        public virtual TravelAgent TravelAgent { get; set; }
        public virtual TravelRequestDetail TravelRequestDetail { get; set; }
    }
}
