//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBookingDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelAgentLogin
    {
        public Nullable<int> AgentLoginId { get; set; }
        public string AgentPswd { get; set; }
    
        public virtual TravelAgent TravelAgent { get; set; }
    }
}
